// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrFjv7FvPhZF7gJU-qCB1lA-o905TOnEw',
    appId: '1:382884696781:web:0c82e230217441f3654f84',
    messagingSenderId: '382884696781',
    projectId: 'smooth-reason-440420-e9',
    authDomain: 'smooth-reason-440420-e9.firebaseapp.com',
    storageBucket: 'smooth-reason-440420-e9.firebasestorage.app',
    measurementId: 'G-SC2SB8RXLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr0BUrSlbv8xSETI4KFSGK8bymHPu62Oo',
    appId: '1:382884696781:android:cfe8d8e6f32f5310654f84',
    messagingSenderId: '382884696781',
    projectId: 'smooth-reason-440420-e9',
    storageBucket: 'smooth-reason-440420-e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU2yPaNk40OmITG2gK5rPSS0xaae8XcJs',
    appId: '1:382884696781:ios:3daa26f8b15c30ad654f84',
    messagingSenderId: '382884696781',
    projectId: 'smooth-reason-440420-e9',
    storageBucket: 'smooth-reason-440420-e9.firebasestorage.app',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU2yPaNk40OmITG2gK5rPSS0xaae8XcJs',
    appId: '1:382884696781:ios:3daa26f8b15c30ad654f84',
    messagingSenderId: '382884696781',
    projectId: 'smooth-reason-440420-e9',
    storageBucket: 'smooth-reason-440420-e9.firebasestorage.app',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrFjv7FvPhZF7gJU-qCB1lA-o905TOnEw',
    appId: '1:382884696781:web:f19e00c0e511f4a8654f84',
    messagingSenderId: '382884696781',
    projectId: 'smooth-reason-440420-e9',
    authDomain: 'smooth-reason-440420-e9.firebaseapp.com',
    storageBucket: 'smooth-reason-440420-e9.firebasestorage.app',
    measurementId: 'G-P7B113QSSX',
  );
}
